AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Streamlit Demo on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  StreamlitFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          STREAMLIT_SERVER_PORT: 8080
      Events:
        ApiEvents:
          Type: HttpApi
      Tracing: Active
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

Outputs:
  StreamlitURL:
    Description: "API Gateway endpoint URL for streamlit function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
  StreamlitFunction:
    Description: "Streamlit Lambda Function ARN"
    Value: !GetAtt StreamlitFunction.Arn
  StreamlitIamRole:
    Description: "Implicit IAM Role created for Streamlit function"
    Value: !GetAtt StreamlitFunctionRole.Arn

